server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /opt/ALB-V2.0.5-SE/html;
    index phone-bar-ex.html index.html;

    location / {
        try_files $uri $uri/ /phone-bar-ex.html;
    }

    location /callbar/ {
        proxy_pass http://[fc00::355:f18]:80/;
    }
}
