server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /opt/ALB-V2.0.5-SE/html;
    index phone-bar-ex.html index.html;

    location / {
        try_files $uri $uri/ /phone-bar-ex.html;
    }

    location /call-center/ {
        proxy_pass http://[fc00::655:9e5a]:8880/call-center/;
    }
    
    location /aicall/ {
        proxy_pass http://[fc00::655:9e5a]:8899/aicall/;

        # ===== 启用跨域配置 =====
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
        add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header Access-Control-Expose-Headers 'Content-Length,Content-Range';
        add_header Access-Control-Allow-Credentials true;
    }

}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name localhost effyic-callcenter-h5.bphc.com.cn effyic-callcenter-h5-pro.bphc.com.cn;

    ssl_certificate     /etc/nginx/ssl/_.bphc.com.cn.cer;
    ssl_certificate_key /etc/nginx/ssl/_.bphc.com.cn.key;

    root /opt/ALB-V2.0.5-SE/html;
    index phone-bar-ex.html index.html;

    location / {
        try_files $uri $uri/ /phone-bar-ex.html;
    }

    location /call-center/ {
        proxy_pass http://[fc00::655:9e5a]:8880/call-center/;
    }
    
    location /aicall/ {
        proxy_pass http://[fc00::655:9e5a]:8899/aicall/;
        
        # ===== 启用跨域配置 =====
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
        add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header Access-Control-Expose-Headers 'Content-Length,Content-Range';
        add_header Access-Control-Allow-Credentials true;
    }

}
