version: '3.8'
services:
  phone-bar-record:
    image: swr.cn-north-4.myhuaweicloud.com/registry-huawei/effyic/phone-record:latest
    container_name: phone-record
    ports:
      - "8902:80"
    restart: always
    pull_policy: always
    volumes:
      #- ./alb/conf:/opt/ALB-V2.0.5-SE/conf:z
      - ./alb/license.xml:/opt/ALB-V2.0.5-SE/license.xml:z
      - ./alb/.LICENSEINFO:/opt/ALB-V2.0.5-SE/.LICENSEINFO:z
      - ./alb/logs:/opt/ALB-V2k.0.5-SE/logs:z
    networks:
      - phone-bar-sdk
networks:
  phone-bar-sdk:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.13.0/24